server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///pachong?characterEncoding=utf-8&userUnicode=true
    username: root
    password: root
logging:
  level:
    top.sellet: info


